name: Build and Publish Go Application

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.0

      - name: Build
        run: go build -o my-app

      - name: Publish to Docker Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            your-docker-registry/your-repo-name:latest
            your-docker-registry/your-repo-name:${{ github.sha }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
